server:
  port: 8088
Spring:
  datasource:
    url: jdbc:mysql://localhost:3306/organization?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimeZone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialact: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: update
    show-sql: true

